// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOG9zPAUrWSswT6yfFOQEiIoPFYtYlrGA',
    appId: '1:434367163208:web:d96859a698ea51d91c217d',
    messagingSenderId: '434367163208',
    projectId: 'farming-assist-7bb6a',
    authDomain: 'farming-assist-7bb6a.firebaseapp.com',
    storageBucket: 'farming-assist-7bb6a.firebasestorage.app',
    measurementId: 'G-TVBJWPNMXZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCpXoKo8iFOQSSeJvjt7iitMVpTTbuvbw',
    appId: '1:434367163208:android:5590884613336fb71c217d',
    messagingSenderId: '434367163208',
    projectId: 'farming-assist-7bb6a',
    storageBucket: 'farming-assist-7bb6a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBlBS3PAf2fYgyBazCv6dmJmpSZxSnZlY',
    appId: '1:434367163208:ios:e44135421c97ab491c217d',
    messagingSenderId: '434367163208',
    projectId: 'farming-assist-7bb6a',
    storageBucket: 'farming-assist-7bb6a.firebasestorage.app',
    iosBundleId: 'com.example.farmingAssist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBlBS3PAf2fYgyBazCv6dmJmpSZxSnZlY',
    appId: '1:434367163208:ios:e44135421c97ab491c217d',
    messagingSenderId: '434367163208',
    projectId: 'farming-assist-7bb6a',
    storageBucket: 'farming-assist-7bb6a.firebasestorage.app',
    iosBundleId: 'com.example.farmingAssist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOG9zPAUrWSswT6yfFOQEiIoPFYtYlrGA',
    appId: '1:434367163208:web:0966621be49561db1c217d',
    messagingSenderId: '434367163208',
    projectId: 'farming-assist-7bb6a',
    authDomain: 'farming-assist-7bb6a.firebaseapp.com',
    storageBucket: 'farming-assist-7bb6a.firebasestorage.app',
    measurementId: 'G-7WZSGSDFT8',
  );
}
