// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDUdihqR9wDFThIOXW-gHS7MjJwQtK6Dg',
    appId: '1:988711799748:web:ed70694e349c6c2185b291',
    messagingSenderId: '988711799748',
    projectId: 'agro-sense-70d67',
    authDomain: 'agro-sense-70d67.firebaseapp.com',
    storageBucket: 'agro-sense-70d67.firebasestorage.app',
    measurementId: 'G-G5J7M1NC4D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoUpa4M1H3Dtcc1lyDPEhBPkAO7-MdRvw',
    appId: '1:988711799748:android:ba5b3d33e064574185b291',
    messagingSenderId: '988711799748',
    projectId: 'agro-sense-70d67',
    storageBucket: 'agro-sense-70d67.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjOs81jE1nWN0AsFQU2n2DMeDy_C9jD_E',
    appId: '1:988711799748:ios:852325e8c05d66ff85b291',
    messagingSenderId: '988711799748',
    projectId: 'agro-sense-70d67',
    storageBucket: 'agro-sense-70d67.firebasestorage.app',
    iosClientId: '988711799748-6prrd7ijv83a6t341692opmvtm6mdn5r.apps.googleusercontent.com',
    iosBundleId: 'com.example.farmingAssist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjOs81jE1nWN0AsFQU2n2DMeDy_C9jD_E',
    appId: '1:988711799748:ios:852325e8c05d66ff85b291',
    messagingSenderId: '988711799748',
    projectId: 'agro-sense-70d67',
    storageBucket: 'agro-sense-70d67.firebasestorage.app',
    iosClientId: '988711799748-6prrd7ijv83a6t341692opmvtm6mdn5r.apps.googleusercontent.com',
    iosBundleId: 'com.example.farmingAssist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDUdihqR9wDFThIOXW-gHS7MjJwQtK6Dg',
    appId: '1:988711799748:web:3d0ced9dffd1afdd85b291',
    messagingSenderId: '988711799748',
    projectId: 'agro-sense-70d67',
    authDomain: 'agro-sense-70d67.firebaseapp.com',
    storageBucket: 'agro-sense-70d67.firebasestorage.app',
    measurementId: 'G-QDR2KYWZVL',
  );

}